version: '3'
services:
  frontend:
    build:
      context: ./cybersec-portal
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./Backend
    ports:
      - "80:80"
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"