apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: safran-backend  # Match the labels used in your backend Deployment
  ports:
    - protocol: TCP
      port: 80           # Port to expose on the Service
      targetPort: 80     # Port that the backend containers are listening on
