apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: safran-frontend  # Match the labels used in your frontend Deployment
  ports:
    - protocol: TCP
      port: 3000          # Port to expose on the Service
      targetPort: 3000    # Port that the frontend containers are listening on (also 3000)
